#version for config and support version 18
version: '3.6'

services:

  apache2-php53:
    image: miguelwill/apache2-53
    #  depends_on:
    #  - db
    volumes:
       - www:/var/www/html
    restart: always
    environment:
      TZ: America/Santiago
      PHP_MEMORY_LIMIT: 512M
      PHP_UPLOAD_MAX_FILESIZE: 60M
      PHP_POST_MAX_SIZE: 90M
      #RELAY_HOST: 172.31.14.20
    ports:
      - 80:80
      - 443:443

volumes:
  www:
