#version for config and support version 18
version: '3.6'

services:

  5.4.44-apache:
    image: miguelwill/5.4.44-apache
    #  depends_on:
    #  - db
    volumes:
       - www:/var/www/html
    restart: always
    environment:
      TZ: America/Santiago
      PHP_MEMORY_LIMIT: 512M
      PHP_UPLOAD_MAX_FILESIZE: 60M
      PHP_POST_MAX_SIZE: 90M
      #RELAY_HOST: 172.31.14.20
    ports:
      - 80:80
      - 443:443

  db:
    image: mariadb:10.3
    restart: always
    volumes:
       - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: l4kj2l3jk4
      MYSQL_DATABASE: sitiodb
      MYSQL_USER: sitiouser
      MYSQL_PASSWORD: sitioPass
      TZ: America/Santiago
    ports:
      - 3306:3306

volumes:
  db-data:
  www:
